steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '--build-arg', 'NEXT_PUBLIC_API_URL=${_BACKEND_URL}',
      '-t', 'gcr.io/$PROJECT_ID/domain-analysis-frontend:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/domain-analysis-frontend:latest',
      '.'
    ]

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/domain-analysis-frontend:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/domain-analysis-frontend:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'domain-analysis-frontend',
      '--image', 'gcr.io/$PROJECT_ID/domain-analysis-frontend:$COMMIT_SHA',
      '--region', 'europe-west1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '512Mi',
      '--cpu', '1',
      '--timeout', '300',
      '--max-instances', '5',
      '--min-instances', '0',
      '--concurrency', '1000',
      '--port', '3000',
      '--set-env-vars', 'NEXT_PUBLIC_API_URL=${_BACKEND_URL}'
    ]

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/domain-analysis-frontend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/domain-analysis-frontend:latest'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 50
  logging: CLOUD_LOGGING_ONLY

# Set build timeout
timeout: 1200s